# Generated by Django 3.0.7 on 2020-07-15 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_type', models.CharField(choices=[('f', 'follow'), ('b', 'block')], max_length=10)),
                ('from_follow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_follow_user', to=settings.AUTH_USER_MODEL)),
                ('to_follow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_follow_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_follow_user', 'to_follow_user')},
            },
        ),
    ]
