# Generated by Django 3.0.7 on 2020-07-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follow_count',
            field=models.IntegerField(default=0),
        ),
    ]
