# Generated by Django 3.0.7 on 2020-07-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_follow_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='follow_count',
            new_name='follower_count',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
    ]
