# Generated by Django 3.0.7 on 2020-07-16 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0003_comment_user'),
        ('posts', '0002_auto_20200715_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_like_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_like_post', to=settings.AUTH_USER_MODEL)),
                ('to_like_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_like_post', to='posts.Post')),
            ],
            options={
                'unique_together': {('from_like_post', 'to_like_post')},
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_like_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_like_comment', to=settings.AUTH_USER_MODEL)),
                ('to_like_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_like_comment', to='comments.Comment')),
            ],
            options={
                'unique_together': {('from_like_comment', 'to_like_comment')},
            },
        ),
    ]
