# Generated by Django 3.0.7 on 2020-07-17 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0003_comment_user'),
        ('likes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='from_like_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_like_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postlike',
            name='to_like_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_like_post', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='from_like_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_like_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='to_like_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_like_comment', to='comments.Comment'),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('from_like_post', 'to_like_post')},
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('from_like_comment', 'to_like_comment')},
        ),
    ]
